yarnPath: .yarn/releases/yarn-3.4.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "@fastify/cookie@*":
    peerDependencies:
      fastify: "*"
  "@fastify/cors@*":
    peerDependencies:
      fastify: "*"
  "@fastify/middie@*":
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  "@fastify-app-tony/monorepo@*":
    dependencies:
      "eslint-plugin-import": "*"
  "eslint-config-react-app@*":
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
