packageExtensions:
  "@fastify-app-tony/monorepo@*":
    dependencies:
      eslint-plugin-import: "*"
  "@fastify/cookie@*":
    peerDependencies:
      fastify: "*"
  "@fastify/cors@*":
    peerDependencies:
      fastify: "*"
  "@fastify/middie@*":
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
