yarnPath: .yarn/releases/yarn-3.4.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "eslint-config-react-app@*":
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "fastify-app-tony@*":
    dependencies:
      "eslint-plugin-import": "*"
