compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@fastify/cookie@*":
    peerDependencies:
      fastify: "*"
  "@fastify/cors@*":
    peerDependencies:
      fastify: "*"
  "@fastify/middie@*":
    dependencies:
      "@types/connect": "*"
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  "@trpc/server@*":
    dependencies:
      fastify: "*"
  mercurius@*:
    peerDependencies:
      fastify: "*"

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.0.cjs
