compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@fastify/autoload@*":
    dependencies:
      fastify: "*"
  "@fastify/cookie@*":
    peerDependencies:
      fastify: "*"
  "@fastify/middie@*":
    dependencies:
      "@types/connect": "*"
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  fastify-plugin@*:
    peerDependencies:
      fastify: "*"
  "@react-router/dev@*":
    dependencies:
      isbot: "*"
  "@mcansh/remix-fastify@*":
    dependencies:
      "@react-router/node": "*"

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.8.1.cjs
